[package]
name = "scryfall"
version = "0.6.1"
authors = ["Mendess2526 <pedro.mendes.26@gmail.com>"]
edition = "2018"
description = "A wrapper around the scryfall magic the gathering api"
license = "MIT"
repository = "https://github.com/Mendess2526/scryfall-rs"
readme = "README.md"
keywords = ["mtg", "Magic", "API", "Scryfall"]
categories = ["api-bindings", "games"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = "0.9"
chrono = { version = "0.4", features = ["serde"] }
percent-encoding = "2.1"
itertools = "0.9"
